- name: Openscap hardening
  hosts: all
  become: yes
  tasks:
    - name: install openscap scanner
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide

    - block:
        - name: run openscap
          command: >
            oscap xccdf eval
            --profile xccdf_org.ssgproject.content_profile_pci-dss
            --results-arf /tmp/oscap-arf.xml
            --report /tmp/oscap-report.html
            --fetch-remote-resources
            /usr/share/xml/scap/ssg/content/ssg-rhel7-ds.xml
      always:
        - name: download report
          fetch:
            src: /tmp/oscap-report.html
            dest: ./{{ inventory_hostname }}.html
            flat: yes
